### ISSUE TITLE
Clicking reply multiple time should only bring up one form

### ISSUE THREAD

**Issue by aarongough** [aarongough/has_threaded_comments#7]

**Comment by noahlitvin** [comment]
Hi, I made a quick fix that hides the "reply" button after the comment box loads: http://gist.github.com/480641

I'm a novice: this certainly isn't the best way to solve the problem, but I figured I should share. Thanks Aaron!

**Comment by aarongough** [comment]
Thanks! I'll check that out when I get the chance. If you would like to, please feel free to fork and patch the change, then send me a pull request. That way I can just add it in, and I will list you as a contributor.

-A

**Comment by noahlitvin** [comment]
Done.

**Comment by aarongough** [comment]
Great! I will pull in the patch on wednesday! Thanks for your work!

**Comment by aarongough** [comment]
This issue is resolved now thanks to Haon99's work!

**Comment by soend** [comment]
Just  updated my plugin but the issue seems to be there still. Reply link is not removed. I checked the 2 lines in the helper and they look like this: 
http://gist.github.com/485005
So no idea whats going wrong.

**Comment by aarongough** [comment]
Are you able to shoot me a link to a publicly accessible version of your project?

**Comment by soend** [comment]
U can have a look of my project here: http://github.com/soend/eor

It looks like :success in link_to_remote is not working..

**Comment by noahlitvin** [comment]
soend: Since this all sits in the vendor folder (for me, at least), I had to restart the server to see changes to the plug-in. Have you tried this?

**Comment by soend** [comment]
Yes, i did complete restart and still nothing. And just to mention, im using jrails.

**Comment by aarongough** [comment]
Also it would be helpful to have a link to a _running_ version of your application. Given that this bit of code is basically all client-side, there's a lot that can go wrong in particular browsers etc...

**Comment by aarongough** [comment]
Ah. I had forgotten you were using jRails. That is more than likely what the problem is. Switch it over to prototype temporarily and confirm whether or not you are still having the problem...

**Comment by soend** [comment]
Ok, mystery solved. It is jrails fault...
And u can see running app here: http://fierce-journey-66.heroku.com/news/1

**Comment by aarongough** [comment]
Ok thought it might be. If I remember correctly jRails does not implement the full suite of Rails Ajax helpers... So that's where the problem is.

Good to hear it's all working!
